// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpoaecolljoowksgkwxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwb2FlY29sbGpvb3drc2drd3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzA3NjIsImV4cCI6MjA3MTcwNjc2Mn0.cDUGv4-yeLj8NeTHdeZV11eAcxJmcSw2zUEyPeDYNY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});